Repository nf-core/website, pull requests merged in 2018-08, with the labels that each got.

#14 Added markdown for instructions to add TEMPLATE branch
  markdown/template_branch.md
Labels: documentation

#17 Reference create subcommand
  markdown/docs.md
  markdown/tools.md
Labels: WIP

#11 added comment to "get started"
  markdown/beginners_guide.md
  public_html/beginners.php
  public_html/index.php
Labels: documentation

#15 How to Nextflow for Dummies
  markdown/howtonextflowfordummies.md
Labels: documentation

#26 Add twitter icon to header
  includes/header.php
  public_html/assets/img/twitter.svg
Labels: enhancement
