Repository nf-core/website, pull requests merged in 2022-10, with the labels that each got.

#1300 Add tentative docs for DSL2 subworkflows
  includes/footer.php
  markdown/developers/subworkflows.md
Labels: documentation

#1321 Add delete label step in the release steps
  markdown/developers/release_checklist.md
Labels: documentation

#1323 Fix typos and grammar in troubleshooting section
  markdown/usage/troubleshooting.md
Labels: documentation

#1328 :memo: Light improvements in wording and layout
  markdown/usage/tutorials/institution.md
Labels: documentation

#1338 Link to correct location for developer guidelines
  public_html/index.php
Labels: bug, documentation

#1334 Fixed broken link in adding_pipelines.md #1318
  markdown/developers/adding_pipelines.md
Labels: documentation

#1345 Update other_tutorials.md
  markdown/developers/gitpod/other_tutorials.md
Labels: documentation

#1360 Fix typos in test_data_guidelines and creating_with_nf_core
  markdown/developers/test_data_guidelines.md
  markdown/developers/tutorials/creating_with_nf_core.md
Labels: documentation

#1359 :memo: :pencil2: Clarify use of local igenomes and fix typo
  markdown/usage/reference_genomes.md
Labels: documentation

#1372 Update training_guide.md
  markdown/developers/training_guide.md
Labels: documentation

#1375 Fix syntax for nf-core modules lint example
  markdown/developers/tutorials/dsl2_modules_tutorial.md
Labels: documentation

#1363 Update data_management.md
  markdown/usage/data_management.md
Labels: documentation

#1383 Update gitpod_introduction.md
  markdown/developers/gitpod/gitpod_introduction.md
Labels: documentation

#1384 Installation instruction
  markdown/usage/installation.md
Labels: documentation, hackathon

#1396 Add info on prettier at tutorial for creating DSL2 modules
  markdown/developers/tutorials/dsl2_modules_tutorial.md
Labels: documentation
