Repository nf-core/website, pull requests merged in 2022-11, with the labels that each got.

#1413 Add `run with` buttons in pipelines pages
  includes/pipeline_page/sidebar.php
  public_html/assets/scss/_nf-core.scss
Labels: front-end, WIP, Ready for Review

#1439 fixed typo in the link to an event #1438
  markdown/events/2023/hackathon-march-2023/index.md
Labels: Ready for Review

#1458 Add Microsoft Azure icon to footer
  includes/footer.php
Labels: front-end
