Repository nf-core/website, pull requests merged in 2023-03, with the labels that each got.

#1653 [FIX] Fixes the extra newline breaking the markdown
  markdown/events/2023/hackathon-march-2023/south-africa-stellenbosch.md
Labels: high-priority

#1531 Bytesize transcript metaboigniter
  markdown/events/2021/bytesize-26-nf-core-metaboigniter.md
Labels: documentation

#1703 Meta combine
  markdown/developers/modules.md
Labels: documentation, hackathon

#1684 Fixed "Edit page on GitHub" 404 error
  includes/header.php
Labels: bug, hackathon

#1688 Moved tutorial pages under "Tutorials" section
  markdown/developers/tutorials/developer_tutorials.md
  markdown/usage/tutorials/nextflow.md
  markdown/usage/tutorials/usage_tutorials.md
Labels: front-end, low-priority, hackathon

#1528 bytesize transcript coproID
  markdown/events/2021/bytesize-29-nf-core-coproid.md
Labels: documentation

#1517 bytesize transcript survey results
  markdown/events/2022/bytesize-survey_results.md
Labels: first-timers-only, documentation

#1525 bytesize34 transcript dsl2 syntax
  markdown/events/2022/bytesize-34-dsl2-syntax.md
Labels: documentation

#1717 Teams notifications
  markdown/usage/introduction.md
Labels: documentation, hackathon, site-content
