Repository nf-core/website, pull requests merged in 2023-08, with the labels that each got.

#1913 Disable AWS File preview for large HTML documents
  src/components/pipeline/AWSFilePreview.astro
Labels: bug, WIP

#1944 Fix #1943 (broken img links in graphic designs)
  src/content/docs/contributing/design_guidelines.md
Labels: bug

#1945 Handle new url style to fix PrevNextButtons and active side bar elements
  src/components/sidebar/SidebarNav.astro
  src/pages/docs/[...doc].astro
  src/pages/events/[event_type].astro
Labels: WIP
