Repository nf-core/website, pull requests merged in 2023-07, with the labels that each got.

#1510 Bytesize transcript dualrnaseq
  markdown/events/2022/bytesize-31-nf-core-dualrnaseq.md
Labels: documentation

#1523 bytesize transcript custom MultiQC
  markdown/events/2022/bytesize-36-multiqc.md
Labels: documentation

#1535 Bytesize transcript dsl2 pipeline starter
  markdown/events/2021/bytesize-24-dsl2-pipeline-starter.md
Labels: documentation

#1823 Explain we don't want MD5 checksums for `versions.yml`
  markdown/developers/modules.md
  public_html/assets/js/aws-s3-explorer.js
  public_html/assets/js/canvas2svg.js
  public_html/assets/js/nf-core-schema-builder.js
  public_html/assets/js/nf-core-schema-launcher.js
  public_html/assets/js/nf-core.js
  public_html/assets/js/transcripts.js
  public_html/assets/scss/_nf-core.scss
Labels: documentation, Ready for Review

#1393 Update DSL2 module tutorial
  markdown/developers/tutorials/dsl2_modules_tutorial.md
  public_html/assets/markdown_assets/developers/dsl2_modules_tutorial/dsl2-mod_03_create_module.png
Labels: documentation

#1835 Add GitHub Action to build static json files and update the markdown cache
  .cache.tar.xz
  .github/workflows/build-components-json.yml
  .github/workflows/build-md-cache-files.yml
  .github/workflows/build-pipelines-json.yml
  bin/build-cache.js
  bin/components.json.js
  bin/pipelines.json.js
  package.json
  public/components.json
  public/pipeline_names.json
  public/pipelines.json
  src/components/octokit.js
  src/config/ignored_repos.yaml
  src/layouts/PipelinePageLayout.astro
  src/pages/[pipeline]/[version]/parameters.astro
Labels: 2023-new-site

#1830 try fixing the ignored exlude setting for ftp deploy
  .github/workflows/web-deploy.yml
  includes/slim_header.php
  public_html/.htaccess
  public_html/assets/js/aws-s3-explorer.js
  public_html/assets/js/canvas2svg.js
  public_html/assets/js/nf-core-schema-builder.js
  public_html/assets/js/nf-core-schema-launcher.js
  public_html/assets/js/nf-core.js
  public_html/assets/js/transcripts.js
  public_html/assets/scss/_nf-core.scss
Labels: 2023-new-site

#1836 add required label to parameter listing
  .cache.tar.xz
  .github/workflows/build-components-json.yml
  .github/workflows/build-md-cache-files.yml
  .github/workflows/build-pipelines-json.yml
  astro.config.mjs
  bin/build-cache.js
  netlify.toml
  public/_redirects
  src/components/InstallCmd.svelte
  src/components/header/Header.astro
  src/components/octokit.js
  src/components/pipeline/PipelineSidebar.astro
  src/components/pipeline/PipelinesListing.svelte
  src/components/schema/SchemaListingElement.svelte
  src/components/schema/SchemaListingGroup.svelte
  src/pages/[pipeline].astro
  src/pages/launch.astro
  src/pages/logo/[title].astro
  src/pages/pipeline_health.astro
  src/pages/stats.astro
  src/styles/main.scss
Labels: 2023-new-site

#1874 trying to fix `nf-core launch`
  .cache.tar.xz
  astro.config.mjs
  public/_redirects
  public/components.json
  public/pipelines.json
  src/pages/[pipeline]/[version]/[...path].astro
  src/pages/launch.astro
Labels: 2023-new-site
