Repository nf-core/website, pull requests merged in 2024-10, with the labels that each got.

#2806 Update hackathon-barcelona.mdx
  sites/main-site/src/content/events/2024/hackathon-barcelona.mdx
Labels: hackathon

#2789 add link to navbar
  sites/main-site/src/components/navbar/Navbar.astro
Labels: WIP

#2822 [WIP] First stab at regulatory topics
  sites/docs/src/content/docs/guidelines/regulatory/overview.md
Labels: WIP

#2831 Regulatory page tweaks
  sites/docs/src/content/docs/guidelines/regulatory/overview.md
Labels: Ready for Review
